# Generated by Django 5.1.2 on 2024-11-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_tesxt',
            new_name='choice_text',
        ),
    ]
