# Generated by Django 5.1.3 on 2024-11-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='ended',
            new_name='is_finished',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='turn',
            new_name='num_turns',
        ),
        migrations.AddField(
            model_name='player',
            name='has_won',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
