# Generated by Django 5.1.3 on 2024-11-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_ended_game_is_finished_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='num_turns',
            new_name='current_player_index',
        ),
        migrations.RemoveField(
            model_name='player',
            name='has_won',
        ),
        migrations.AddField(
            model_name='game',
            name='target_score',
            field=models.IntegerField(default=21),
        ),
    ]
