# Generated by Django 5.1.3 on 2024-11-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_num_turns_game_current_player_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_finished',
            new_name='ended',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='current_player_index',
            new_name='turn',
        ),
        migrations.RemoveField(
            model_name='game',
            name='target_score',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
